import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { MenubarDemo } from '@/components/MenuBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className='flex flex-col items-center justify-center bg-zinc-500'>
          <header className="flex justify-center align-center flex-col h-32">
            <h1 className=" text-center text-black text-5xl my-5">Atendimento Padrão CHAT</h1>
          </header>
          <MenubarDemo />
          {children}
        </main>
      </body>
    </html>
  )
}
